### PR TITLE
Added new directive {mname} and cmd line arg /echo

### PR DESCRIPTION
**Pull request by The-Futurist**
…re the build took place.

### CODE REVIEW

**Comment by The-Futurist** [comment]
I tested this locally and it appeared solid.

**Comment by The-Futurist** [comment]
@ygoe Hi, did you notice my pull request yet?

**Comment by ygoe** [comment]
@Korporal I did notice it and its notification e-mail is in my inbox with a flag on it, I just didn't get to take a closer look yet. I'll try to do that during the next week.

**Comment by ygoe** [comment]
I have included your changes manually due to conflicting code style. Your suggested parameter and placeholder names are unchanged though.

**Pull request closed without merging**
